trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "===== Azure Account ====="
      az account show

      echo "===== Current Subscription ====="
      az account show --query "{Subscription:id, Name:name, Tenant:tenantId}"

      echo "===== Resource Groups ====="
      az group list -o table

      wget https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip
      unzip -o terraform_1.9.8_linux_amd64.zip
      sudo mv terraform /usr/local/bin/

      terraform version
      terraform init
      terraform validate
      terraform apply -auto-approve